import React from 'react'
import Head from 'next/head';
import Header from '@/components/header/Header';
import styles from './Layout.module.scss';
import { useRouter } from 'next/router';
import { Orbitron } from 'next/font/google';
import clsx from 'clsx';
// npm i clsx

const orbitron = Orbitron({ subsets: ['latin'], wegith: ['400', '500'], preload: true, variable: '--font-orbitron'})
// variable 등록하지 않고 해당 컴포넌트에 객채명.clasName을 등록하면
// 해당 컴포넌트 안쪽에 있는 모든 폰트에는 구글 웹폰트 적용
// variable을 등록하고 컴포넌트에 객채명.variable을 등록하면 컴포넌트에서 scss 모듈에
// var(--font-객체명) 형식으로 지정한 폰트만 선별적으로 구글폰트 적용



function Layout( { children } ) {
  const router = useRouter();
  console.log(router);

  const title = router.asPath.split('/')[1];
  const Title = (title.charAt(0).toUpperCase() + title.slice(1)) || 'Home';

  return (
    <>
      <Head>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
        <title>{Title} Page</title>
			</Head>

			<Header />
			<main className={clsx(styles.layout, orbitron.variable)}>
				<h1>{Title}</h1>
				{children}
			</main>
    </>
    
  )
}

export default Layout